### ISSUE TITLE
Create more generic disk benchmark script

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-dramble#185]
The microsd-benchmark.sh script is geared towards microSD cards using the built-in reader... but CM4s and the Pi 4 with USB 3.0 drives makes for a much faster experience, and I like to benchmark other devices besides the microSD card.

Initially, I'm thinking of cloning the script and calling the new one `disk-benchmark.sh`, then making it so you can add parameters like the device name (e.g. `/dev/sda1`) and mount path (e.g. `/mnt/usbdrive`).

**Comment by Reflective-Dimensions** [comment]
Sorry for the trouble. I'm new and wanted to follow you and your bramble, dramble projects. . I must have hit something I thought was something else out of pure lack of understanding. Thank You.On Jan 26, 2021 05:28, "stale[bot]" <notifications@github.com> wrote:
This issue has been marked 'stale' due to lack of recent activity. If there is no further activity, the issue will be closed in another 30 days. Thank you for your contribution!
Please read this blog post to see the reasons why I mark issues as stale.
